# Generated by Django 5.0.7 on 2024-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetellGIAgentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('complete_transfer', 'Complete with Transfer'), ('complete_no_transfer', 'Complete without Transfer'), ('other', 'Other')], max_length=20)),
                ('transfer_reason', models.CharField(blank=True, choices=[('live_agent', 'Live Agent Requested'), ('payment', 'Payment'), ('rx_status', 'RX Status'), ('other', 'Other')], max_length=20)),
                ('complete_reason', models.CharField(blank=True, choices=[('prep_directions', 'Prep Directions'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
