# Generated by Django 5.0.7 on 2024-08-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetellZepboundAgentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('complete_transfer', 'Complete with Transfer'), ('complete_no_transfer', 'Complete without Transfer'), ('other', 'Other')], max_length=20)),
                ('transfer_reason', models.CharField(blank=True, max_length=20)),
                ('complete_reason', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
